apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bvyzwt7kf-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bvyzwt7kf-dotnet-basic-gitops